services:
  db:
    #image: postgres:16
    image: pgvector/pgvector:pg16
    container_name: reviews-postgres
    ports:
      - "5432:5432"
    # Note:
    # Postgres environment variables only respected when volume first created,
    #  after which the database and user are already created.
    # Also, changing POSTGRES_USER doesn't change the container's linux system user, and complicates things.
    #  ref: https://github.com/docker-library/docs/tree/master/postgres#postgres_user
    #  ref: https://github.com/docker-library/docs/tree/master/postgres#arbitrary---user-notes
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: reviews
#      POSTGRES_DB: reviews
    volumes:
      - reviews-postgres:/var/lib/postgresql/data
      - ./data/export:/export
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - net
  graphqlapi:
    depends_on:
      db:
        condition: service_healthy
      modelapi:
        condition: service_healthy
    image: amazonreviews/graphql-api:latest
    container_name: reviews-graphql-api
    ports:
      - "4000:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: reviews
      MODEL_API_URL: http://modelapi:5000
    networks:
      - net
  modelapi:
    image: amazonreviews/model-api:latest
    container_name: reviews-model-api
    ports:
      - "5000:5000"
    networks:
      - net

volumes:
  reviews-postgres:

networks:
  net:
    driver: bridge
