services:
  db:
    image: pgvector/pgvector:pg16
    container_name: reviews-pg-test
    ports:
      - "5433:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      #POSTGRES_PASSWORD: reviews
      #POSTGRES_DB: reviews
    volumes:
      - reviews-pg-test:/var/lib/postgresql/data
      - ./src/test/resources/database/export:/export
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - net
  modelapi:
    image: amazonreviews/model-api:latest
    container_name: reviews-model-api-test
    ports:
      - "5001:5000"
    networks:
      - net

volumes:
  reviews-pg-test:

networks:
  net:
    driver: bridge
