services:
  db:
    image: postgres:16
    container_name: reviews-postgres
    ports:
      - "5432:5432"
    # Note:
    # Postgres environment variables only respected when volume first created,
    #  after which the database and user are already created.
    # Also, changing POSTGRES_USER doesn't change the container's linux system user, and complicates things.
    #  ref: https://github.com/docker-library/docs/tree/master/postgres#postgres_user
    #  ref: https://github.com/docker-library/docs/tree/master/postgres#arbitrary---user-notes
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: reviews
#      POSTGRES_DB: reviews
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./data/export:/export
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  postgres:
