CREATE TABLE IF NOT EXISTS itemimage (
  itemimage_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thumb TEXT,
  large TEXT,
  variant TEXT,
  hires TEXT
);
COPY itemimage FROM '/export/itemimage.csv' WITH CSV DELIMITER E'\x1e' QUOTE E'\x1f' NULL AS '' HEADER;