CREATE TABLE IF NOT EXISTS itemauthor (
  itemauthor_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  avatar TEXT,
  fullname TEXT,
  about TEXT[]
);
COPY itemauthor FROM '/export/itemauthor.csv' WITH CSV DELIMITER E'\x1e' QUOTE E'\x1f' NULL AS '' HEADER;