CREATE TABLE IF NOT EXISTS review (
  review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rating SMALLINT,
  title TEXT,
  bodytext TEXT,
  asin TEXT,
  parent_asin TEXT,
  time_stamp BIGINT,
  helpful_vote BIGINT,
  verified_purchase BOOLEAN
);
COPY review FROM '/export/review.csv' WITH CSV DELIMITER E'\x1e' QUOTE E'\x1f' NULL AS '' HEADER;