-- Uses postgres extension pgvector: https://github.com/pgvector/pgvector
-- Hidden size 768 pre-defined when training model: models/blair-roberta-base/config.json
CREATE EXTENSION IF NOT EXISTS vector;
CREATE TABLE IF NOT EXISTS item_embed (
  item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title vector(768)
);
COPY item_embed FROM '/export/item_embed.csv' WITH CSV DELIMITER E'\x1e' QUOTE E'\x1f' NULL AS '' HEADER;
CREATE INDEX ON item_embed USING hnsw (
  title vector_ip_ops
);
ANALYZE item_embed;